# Generated by Django 2.2.7 on 2019-11-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered at'),
        ),
    ]
