# Generated by Django 2.2.7 on 2019-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20191120_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='chat',
            field=models.ManyToManyField(blank=True, null=True, related_name='Message', to='frontend.Chat'),
        ),
    ]
